Scrum 2
elagarrigue/AyDS22-AK-Winchester2 pull request #1
Opened 2022-04-12 22:36 UTC by TomasFelp

2022-04-14 23:39 UTC, elagarrigue requested changes
Bien en general, lo más importante es cumplir con Inversión de Dependencias

2022-04-14 23:39 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/entities/SpotifySong.kt
> +  override var releasedPrecisionDate: DatePrecision
Mejor definirlo como val, ya que no va a cambiar (debajo de imageUrl para no tener que nombrar el parámetro)

2022-04-14 23:39 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/external/spotify/tracks/SpotifyToSongResolver.kt
> +        return DatePrecision.valueOf(album[RELEASE_DATE_PRECISION].asString.toUpperCase())
Esto funciona ahora, pero podría cambiar. Si cambia el string "date" por ejemplo a "a_date", tendrían que cambiar el modelo en vez de esta clase. Mejor hacer un when y verificar explícitamente qué constante corresponde a qué valor del enumerado.

2022-04-14 23:39 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/local/spotify/sqldb/SpotifyTableConstants.kt
> +            "$PRECISION_DATE_COLUMN string)"
debería ser integer

2022-04-14 23:39 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/view/DateDescription/DatePrecisionText.kt
> +    }
```suggestion
    override fun getTextDate(date: String, precision: DatePrecision) =
        when (precision) {
            DatePrecision.DAY -> getYearMonthDay(date)
            DatePrecision.MONTH -> getYearMonth(date)
            DatePrecision.YEAR -> getYear(date)
        }
```

2022-04-14 23:39 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/view/DateDescription/DatePrecisionText.kt
> +        var new_month = date.substringAfterLast("-")
utilizar camelCase para el nombre de las variables

2022-04-14 23:39 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/view/DateDescription/DatePrecisionText.kt
> +    fun esBisiesto(year: Int) : String{
mejor en inglés, por uniformidad
```suggestion
    fun isLeapYear(year: Int) : String{
```

2022-04-14 23:39 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/view/DateDescription/DatePrecisionText.kt
> +object DateTextImpl : DateText{
En general vamos a evitar los singletons en este tipo de clases, podríamos querer otras implementaciones. Además, debería ser internal
```suggestion
internal class DateTextImpl : DateText{
```

2022-04-14 23:39 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/view/SongDescriptionHelperImpl.kt
> +    var dateConverter: DateText
No hace falta exponer esta propiedad

2022-04-14 23:39 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/view/SongDescriptionHelperImpl.kt
> +    override var dateConverter: DateText = DateTextImpl
No se cumple con ID, se depende de `DateTextImpl`. Crear la instancia en el injector, y pasarla por constructor
```
internal class SongDescriptionHelperImpl(private val dateConverter: DateText) : SongDescriptionHelper 
```

2022-04-17 17:15 UTC, elagarrigue requested changes

2022-04-17 17:15 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/external/spotify/tracks/SpotifyToSongResolver.kt
> +        return when (album[RELEASE_DATE_PRECISION].asString){
No están cumpliendo con SRP, OC, DI. Muevan la lógica a otra clase, inyecten la dependencia.

2022-04-17 17:15 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/external/spotify/tracks/SpotifyToSongResolver.kt
> +            else -> {DatePrecision.valueOf("DAY")}
No es un buen valor por defecto. Si existe la precisión "década", tendríamos una excepción en la view al hacer el split. Mejor disparar una excepción.

2022-04-18 13:37 UTC, elagarrigue requested changes
Últimos detalles. Agregar descripción en el PR, resumen del objetivo del mismo.

2022-04-18 13:37 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/external/spotify/tracks/SongPrecisionDateHelper.kt
> +            YEAR -> DatePrecision.valueOf("YEAR")
```suggestion
            DAY -> DatePrecision.valueOf(DAY)
            MONTH -> DatePrecision.valueOf(MONTH)
            YEAR -> DatePrecision.valueOf(YEAR)
```

2022-04-18 13:37 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/external/spotify/tracks/SpotifyToSongResolver.kt
> +            Log.i("JSON","Error " +e.message)
Revertir log

2022-04-18 13:37 UTC, elagarrigue commented on app/src/main/java/ayds/winchester/songinfo/home/model/repository/external/spotify/tracks/SpotifyToSongResolver.kt
> +import android.util.Log
Revertir

2022-04-18 17:31 UTC, SeleneGonzalo commented
Se realizaron cambios en el proyecto cumpliendo con los principios SOLID (más específicamente la inversión de dependencias). Se agregó al modelo la propiedad "release_date_precision".

2022-04-18 18:09 UTC, elagarrigue approved these changes
Ahí quedó 🙌🏽 . Recuerden para la próxima agregar un comentario en el PR.

2022-04-18 18:09 UTC, merged